import type { Context } from "grammy";
import { keyboardManager } from "./keyboards/keyboard-manager.js";
import { MAIN_BUTTONS } from "./keyboards/main-reply-keyboard.js";
import { getStoredModel } from "../app/services/model-selection-service.js";
import { formatModelForButton } from "../app/types/model.js";
import { getTopicRuntimeContext } from "../app/services/topic-runtime-context.js";
import { findTelegramTopicBindingByThread } from "../app/services/telegram-topic-store.js";
import {
  AGENT_MODE_BUTTON_TEXT_PATTERN,
  CONTEXT_BUTTON_TEXT_PATTERN,
  QUEUED_PROMPT_BUTTON_TEXT_PATTERN,
  VARIANT_BUTTON_TEXT_PATTERN,
} from "./message-patterns.js";

export type ReplyKeyboardScope = "main" | "general" | "ai-topic";

export type ReplyKeyboardInteraction = {
  isControl: boolean;
  scope: ReplyKeyboardScope;
  text: string;
  controlId?: string;
};

export type ReplyKeyboardContext = {
  scope: ReplyKeyboardScope;
  sessionId?: string;
};

function normalize(text: string): string {
  return text.normalize("NFKC").replace(/[\u200B-\u200D\uFEFF]/g, "").replace(/\uFE0F/g, "").replace(/\s+/g, " ").trim();
}

function keyboardButtonTexts(keyboard: unknown): string[] {
  if (!Array.isArray(keyboard)) return [];
  return keyboard.flatMap((row) => {
    if (!Array.isArray(row)) return [];
    return row.flatMap((button) => {
      if (typeof button === "string") return [button];
      if (typeof button === "object" && button !== null && "text" in button) {
        const value = Reflect.get(button, "text");
        return typeof value === "string" ? [value] : [];
      }
      return [];
    });
  });
}

function currentGlobalModelButton(): string {
  const model = getStoredModel();
  return model.providerID && model.modelID
    ? formatModelForButton(model.providerID, model.modelID, model.name)
    : "🧠 Model";
}

function staticControlMap(): ReadonlyMap<string, string> {
  const controls = new Map<string, string>();
  const add = (text: string, id: string): void => { controls.set(normalize(text), id); };
  add(MAIN_BUTTONS.history, "history");
  add(MAIN_BUTTONS.newChat, "new-chat");
  add(MAIN_BUTTONS.mainSettings, "main-settings");
  add(MAIN_BUTTONS.topicSettings, "topic-settings");
  add(MAIN_BUTTONS.imageAi, "image-ai");
  add(MAIN_BUTTONS.deleteChat, "delete-chat");
  add(MAIN_BUTTONS.pause, "pause");
  add(MAIN_BUTTONS.resume, "resume");
  add(MAIN_BUTTONS.abort, "abort");
  add("🧠 Model Center", "model-center");
  add("❌ Cancel", "cancel");
  add(MAIN_BUTTONS.compact(true), "compact");
  add(MAIN_BUTTONS.compact(false), "compact");
  return controls;
}

export async function resolveReplyKeyboardContext(ctx: Context): Promise<ReplyKeyboardContext> {
  const chatId = ctx.chat?.id;
  const threadId = ctx.message?.message_thread_id;
  if (typeof chatId !== "number") return { scope: "main" };

  if (typeof threadId !== "number" || threadId <= 1) {
    return keyboardManager.isTopicMode(chatId)
      ? { scope: "general" }
      : { scope: "main" };
  }

  const runtime = getTopicRuntimeContext();
  if (runtime?.chatId === chatId && runtime.threadId === threadId && runtime.sessionId) {
    return { scope: "ai-topic", sessionId: runtime.sessionId };
  }

  const binding = await findTelegramTopicBindingByThread(chatId, threadId);
  if (binding) return { scope: "ai-topic", sessionId: binding.sessionId };

  return { scope: "main" };
}

function getRenderedLabels(context: ReplyKeyboardContext): Set<string> {
  const keyboard = context.scope === "ai-topic"
    ? keyboardManager.getKeyboard(context.sessionId)
    : context.scope === "general"
      ? keyboardManager.getKeyboard()
      : null;
  const built = keyboard && typeof (keyboard as { build?: () => unknown }).build === "function"
    ? (keyboard as { build: () => unknown }).build()
    : keyboard;
  return new Set(keyboardButtonTexts(built).map(normalize));
}

function isDynamicAiTopicControl(text: string): string | undefined {
  // These controls can be rendered by Topic-specific menus/keyboard states
  // that are not guaranteed to survive a process restart. Once the inbound
  // message is proven to belong to an AI Topic, their shape is part of the
  // Reply Keyboard protocol and must be consumed before prompt routing.
  if (AGENT_MODE_BUTTON_TEXT_PATTERN.test(text)) return "agent-mode";
  if (VARIANT_BUTTON_TEXT_PATTERN.test(text)) return "variant";
  if (CONTEXT_BUTTON_TEXT_PATTERN.test(text)) return "context";
  if (QUEUED_PROMPT_BUTTON_TEXT_PATTERN.test(text)) return "queued-prompt";
  return undefined;
}

/**
 * Authoritative boundary between Telegram Reply Keyboard controls and prompts.
 *
 * Telegram sends KeyboardButton presses as ordinary text messages. The safest
 * possible discriminator is therefore the exact rendered keyboard for the
 * current Topic/session. AI-topic dynamic controls are additionally covered
 * by their protocol patterns because those labels can be generated by menus
 * and may outlive the in-memory keyboard registry after a restart.
 */
export async function classifyReplyKeyboardInteraction(ctx: Context): Promise<ReplyKeyboardInteraction> {
  const raw = ctx.message?.text;
  const text = typeof raw === "string" ? normalize(raw) : "";
  const context = await resolveReplyKeyboardContext(ctx);
  if (!text) return { isControl: false, scope: context.scope, text };

  const staticControl = staticControlMap().get(text);
  if (staticControl) return { isControl: true, scope: context.scope, text, controlId: staticControl };

  const rendered = getRenderedLabels(context);
  if (rendered.has(text)) {
    return { isControl: true, scope: context.scope, text, controlId: "keyboard-control" };
  }

  if (context.scope === "ai-topic") {
    const dynamicControl = isDynamicAiTopicControl(text);
    if (dynamicControl) {
      return { isControl: true, scope: context.scope, text, controlId: dynamicControl };
    }
  }

  if (text === normalize(currentGlobalModelButton())) {
    return { isControl: true, scope: context.scope, text, controlId: "model" };
  }

  return { isControl: false, scope: context.scope, text };
}

export async function isReplyKeyboardControl(ctx: Context): Promise<boolean> {
  return (await classifyReplyKeyboardInteraction(ctx)).isControl;
}
