import { InputFile, type Context } from "grammy";
import { downloadPhoto, downloadRepliedPhoto } from "../services/media-ai-service.js";
import { generateImageWithFallback, editImageWithFallback, hasActiveImageAiProvider } from "../../app/services/image-ai-provider-service.js";

export { downloadPhoto } from "../services/media-ai-service.js";
export async function editImage(image: Buffer, mimeType: string, prompt: string) { return editImageWithFallback(image, mimeType, prompt); }
export async function isMediaAiConfigured(): Promise<boolean> { return hasActiveImageAiProvider("generate") || hasActiveImageAiProvider("edit"); }

const GENERATE_INTENT = /(?:\b(?:i|i'd|i would|please|can you|could you|want|need)\b[^\n]{0,80}\b(?:image|picture|photo)\b|\b(?:image|picture|photo)\b[^\n]{0,100}\b(?:generate|create|draw|make|render|produce)\b|(?:می.?خوام|می.?خواهم|برام|یه|یک)[^\n]{0,50}\b(?:تصویر|عکس|image|picture|photo)\b[^\n]{0,100}\b(?:بساز|بسازیم|بکش|ایجاد|تولید|جنریت|ساخت)\b|\b(?:generate|create|draw|make|render|produce|بساز|بکش|ایجاد|تولید|جنریت)\b[^\n]{0,100}\b(?:تصویر|عکس|image|picture|photo)\b)/iu;
const EDIT_INTENT = /(?:^|\s)(?:edit|change|modify|remove|replace|add|delete|background|backdrop|retouch|enhance|upscale|crop|resize|transform|style|ویرایش|تغییر|حذف|جایگزین|اضافه|پس.?زمینه|بک.?گراند|رتوش|بهبود|بزرگ.?نمایی|برش|تبدیل)(?:\s|$)/iu;
const REFERENCE_INTENT = /(?:this photo|this image|based on this|using this|from this photo|روی همین عکس|بر اساس این عکس|با استفاده از این عکس|از روی این عکس)/iu;

export function isImageGenerationIntent(text: string): boolean { return GENERATE_INTENT.test(text.trim()); }
export function isImageEditIntent(text: string): boolean { return EDIT_INTENT.test(text); }
export function classifyImageIntent(text: string, hasSourceImage: boolean): "generate" | "edit" | null { const value = text.trim(); if (!value) return null; if (!hasSourceImage) return isImageGenerationIntent(value) ? "generate" : null; if (REFERENCE_INTENT.test(value) || isImageEditIntent(value)) return "edit"; if (isImageGenerationIntent(value)) return "generate"; return null; }
function commandArguments(ctx: Context): string { return (ctx.message?.text ?? "").replace(/^\/\w+(?:@\w+)?\s*/u, "").trim(); }
function mediaNotConfiguredMessage(): string { return "🎨 Image AI is not configured. Open /providers → 🎨 Image AI and configure a provider."; }
async function sendGeneratedImage(ctx: Context, prompt: string): Promise<void> { if (!(await hasActiveImageAiProvider("generate"))) { await ctx.reply(mediaNotConfiguredMessage()); return; } if (!prompt) { await ctx.reply("Usage: /image <prompt>"); return; } await ctx.replyWithChatAction("upload_photo"); const result = await generateImageWithFallback(prompt); await ctx.replyWithPhoto(new InputFile(result.buffer, `generated.${result.mimeType.split("/")[1] ?? "png"}`), { caption: "🎨 Generated with Image AI" }); }
export async function imageCommand(ctx: Context): Promise<void> { try { await sendGeneratedImage(ctx, commandArguments(ctx)); } catch (error) { await ctx.reply(`❌ Image generation failed: ${error instanceof Error ? error.message : String(error)}`); } }
export async function editCommand(ctx: Context): Promise<void> { if (!(await hasActiveImageAiProvider("edit"))) { await ctx.reply(mediaNotConfiguredMessage()); return; } const prompt = commandArguments(ctx); if (!prompt) { await ctx.reply("Usage: reply to a photo with /edit <instruction>"); return; } try { const source = await downloadRepliedPhoto(ctx); await ctx.replyWithChatAction("upload_photo"); const result = await editImageWithFallback(source.buffer, source.mimeType, prompt); await ctx.replyWithPhoto(new InputFile(result.buffer, `edited.${result.mimeType.split("/")[1] ?? "png"}`), { caption: "✨ Edited with Image AI" }); } catch (error) { await ctx.reply(`❌ Image editing failed: ${error instanceof Error ? error.message : String(error)}`); } }
export async function handleImageTextPrompt(ctx: Context, prompt: string): Promise<boolean> { if (classifyImageIntent(prompt, false) !== "generate") return false; try { await sendGeneratedImage(ctx, prompt); } catch (error) { await ctx.reply(`❌ Image generation failed: ${error instanceof Error ? error.message : String(error)}`); } return true; }
export async function handlePhotoCaptionMessage(ctx: Context, prompt: string): Promise<void> { const intent = classifyImageIntent(prompt, true); try { if (intent === "generate") { await sendGeneratedImage(ctx, prompt); return; } if (intent !== "edit") return; if (!(await hasActiveImageAiProvider("edit"))) { await ctx.reply(mediaNotConfiguredMessage()); return; } const source = await downloadPhoto(ctx); await ctx.replyWithChatAction("upload_photo"); const result = await editImageWithFallback(source.buffer, source.mimeType, prompt); await ctx.replyWithPhoto(new InputFile(result.buffer, `edited.${result.mimeType.split("/")[1] ?? "png"}`), { caption: "✨ Edited with Image AI" }); } catch (error) { await ctx.reply(`❌ Image ${intent === "generate" ? "generation" : "editing"} failed: ${error instanceof Error ? error.message : String(error)}`); } }
export async function editPhotoMessage(ctx: Context, prompt: string): Promise<void> { if (!(await hasActiveImageAiProvider("edit"))) { await ctx.reply(mediaNotConfiguredMessage()); return; } if (!prompt) { await ctx.reply("Usage: send a photo with /edit <instruction>."); return; } try { const source = await downloadPhoto(ctx); await ctx.replyWithChatAction("upload_photo"); const result = await editImageWithFallback(source.buffer, source.mimeType, prompt); await ctx.replyWithPhoto(new InputFile(result.buffer, `edited.${result.mimeType.split("/")[1] ?? "png"}`), { caption: "✨ Edited with Image AI" }); } catch (error) { await ctx.reply(`❌ Image editing failed: ${error instanceof Error ? error.message : String(error)}`); } }
