import type { CommandContext, Context } from "grammy";
import { InlineKeyboard } from "grammy";
import { configureGroqStt, deleteCustomProvider, discoverModels, isGroqSttConfigured, removeGroqStt, listCustomProviders, saveCustomProvider, syncOpenCodeCustomConfig } from "../../app/services/custom-provider-service.js";
import { configureBuiltInImageAiProvider, configureImageAiProvider, IMAGE_AI_PROVIDER_IDS, listImageAiProviders, removeImageAiProvider } from "../../app/services/image-ai-provider-service.js";
import { reconcileStoredModelSelection } from "../../app/services/model-selection-service.js";
import { config } from "../../config.js";
import { findServerPid, killServerProcess, resolveLocalOpencodeTarget, startLocalOpencodeServer } from "../../opencode/process.js";
import { logger } from "../../utils/logger.js";
import { clearIntegrationWizard } from "./integrations-command.js";
import { buildAdvancedSettingsView } from "../menus/settings-menu.js";
import { replyWithInlineMenu } from "../menus/inline-menu.js";

const GEMINI_PROVIDER_ID = "gemini";
const GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai";
const GEMINI_MODEL = "gemini-3.1-flash-lite";
const LEGACY_GEMINI_IMAGE_PROVIDER_ID = "gemini-image";
interface PendingProvider { step: "name" | "url" | "key" | "groq-stt-key" | "gemini-chat-key" | "image-pollinations-key" | "image-huggingface-key" | "image-custom-base-url" | "image-custom-model" | "image-custom-edit-model" | "image-custom-key"; name?: string; baseURL?: string; apiKey?: string; model?: string; editModel?: string; messageId: number; }
const pending = new Map<number, PendingProvider>();
function callbackMessageId(ctx: Context): number | null { const message = ctx.callbackQuery?.message; if (!message || !("message_id" in message)) return null; return typeof message.message_id === "number" ? message.message_id : null; }
function wizardKeyboard(): InlineKeyboard { return new InlineKeyboard().text("❌ Cancel", "provider:cancel").text("← Providers", "provider:menu"); }
export function isProviderWizardActive(chatId: number): boolean { return pending.has(chatId); }
export function clearProviderWizard(chatId: number): void { pending.delete(chatId); }
async function deleteInput(ctx: Context): Promise<void> { const messageId = ctx.message?.message_id; if (ctx.chat?.id && messageId) await ctx.api.deleteMessage(ctx.chat.id, messageId).catch(() => {}); }
async function editWizard(ctx: Context, messageId: number, text: string): Promise<void> { if (!ctx.chat?.id) return; await ctx.api.editMessageText(ctx.chat.id, messageId, text, { reply_markup: wizardKeyboard() }); }
async function restartOpenCodeAfterProviderChange(): Promise<void> { const configPath = await syncOpenCodeCustomConfig(); process.env.OPENCODE_CONFIG = configPath; const target = resolveLocalOpencodeTarget(config.opencode.apiUrl); if (!target) return; const pid = await findServerPid(target.port); if (pid) await killServerProcess(pid); await new Promise((resolve) => setTimeout(resolve, 500)); startLocalOpencodeServer(target).unref(); await reconcileStoredModelSelection({ forceCatalogRefresh: true }).catch((error) => logger.warn("[Providers] Model catalog refresh failed:", error)); }

async function renderImageAiMenu(ctx: Context, messageId?: number, notice?: string): Promise<void> {
  const providers = await listImageAiProviders(); const status = new Map(providers.map((p) => [p.id, p])); const keyboard = new InlineKeyboard();
  const poll = status.get(IMAGE_AI_PROVIDER_IDS.POLLINATIONS_ID); const hf = status.get(IMAGE_AI_PROVIDER_IDS.HUGGINGFACE_ID); const custom = status.get(IMAGE_AI_PROVIDER_IDS.CUSTOM_ID);
  keyboard.text(poll?.active ? "🎨 Pollinations · Active ✅" : "🎨 Pollinations", "provider:image:pollinations:configure").row();
  keyboard.text(hf?.active ? "🤗 Hugging Face · Active ✅" : "🤗 Hugging Face", "provider:image:huggingface:configure").row();
  keyboard.text(custom?.active ? "🧩 Custom Image AI · Active ✅" : "🧩 Custom Image AI", "provider:image:custom:configure").row();
  keyboard.text("← Providers", "provider:menu");
  const lines = ["🎨 Image AI", "", "Independent image generation/editing providers with automatic fallback.", "", poll?.active ? `✅ Pollinations — ${poll.model}${poll.editModel ? ` / edit: ${poll.editModel}` : ""}` : "⚪ Pollinations — not configured", hf?.active ? `✅ Hugging Face — ${hf.model}` : "⚪ Hugging Face — not configured", custom?.active ? `✅ Custom Image AI — ${custom.model}${custom.editModel ? ` / edit: ${custom.editModel}` : ""}` : "⚪ Custom Image AI — not configured", "", "Pollinations: generation + editing. Hugging Face: generation fallback."];
  const text = `${notice ? `${notice}\n\n` : ""}${lines.join("\n")}`; const target = messageId ?? callbackMessageId(ctx); if (target !== null && ctx.chat?.id) { await ctx.api.editMessageText(ctx.chat.id, target, text, { reply_markup: keyboard }); return; } await ctx.reply(text, { reply_markup: keyboard });
}
async function renderProvidersMenu(ctx: Context, messageId?: number, notice?: string): Promise<void> {
  const providers = await listCustomProviders(); const visibleCustom = providers.filter((p) => p.id !== GEMINI_PROVIDER_ID && p.id !== LEGACY_GEMINI_IMAGE_PROVIDER_ID); const gemini = providers.some((p) => p.id === GEMINI_PROVIDER_ID && p.models.some((m) => m.id === GEMINI_MODEL)); const groqStt = await isGroqSttConfigured(); const imageProviders = await listImageAiProviders(); const activeImage = imageProviders.filter((p) => p.active);
  const keyboard = new InlineKeyboard().text("➕ Add custom provider", "provider:add"); keyboard.row().text(gemini ? "🤖 Gemini · Active ✅" : "🤖 Gemini", "provider:gemini:configure"); keyboard.row().text("🎨 Image AI", "provider:image:menu"); keyboard.row().text(groqStt ? "🎤 Configure Groq Voice STT · ✅ Active" : "🎤 Configure Groq Voice STT", groqStt ? "provider:stt:groq:remove" : "provider:stt:groq:add"); for (const provider of visibleCustom) keyboard.row().text(`🧠 ${provider.name}`, `provider:view:${provider.id}`).text("🗑️", `provider:delete:${provider.id}`); keyboard.row().text("← Advanced", "provider:advanced").text("✖ Close", "provider:close");
  const body = visibleCustom.length ? `🔌 Custom Providers\n\n${visibleCustom.map((p) => `• ${p.name} — ${p.baseURL} — ${p.models.length} models`).join("\n")}` : "🔌 Custom Providers\n\nNo custom providers configured yet."; const geminiLine = gemini ? `🤖 Gemini: Active · ${GEMINI_MODEL} (Free Tier)` : "🤖 Gemini: Not configured"; const sttLine = groqStt ? "🎤 Voice transcription: Groq Whisper Large V3 · Active" : "🎤 Voice transcription: Not configured"; const imageLine = activeImage.length ? `🎨 Image AI: ${activeImage.map((p) => p.name).join(", ")} · Active` : "🎨 Image AI: Not configured"; const text = `${notice ? `${notice}\n\n` : ""}${body}\n\n${geminiLine}\n${sttLine}\n${imageLine}`; const target = messageId ?? callbackMessageId(ctx); if (target !== null && ctx.chat?.id) { await ctx.api.editMessageText(ctx.chat.id, target, text, { reply_markup: keyboard }); return; } await ctx.reply(text, { reply_markup: keyboard });
}
export async function providersCommand(ctx: CommandContext<Context>): Promise<void> { const chatId = ctx.chat?.id; if (chatId) { clearProviderWizard(chatId); clearIntegrationWizard(chatId); } await renderProvidersMenu(ctx as Context); }

export async function handleProviderCallback(ctx: Context): Promise<boolean> {
  const data = ctx.callbackQuery?.data ?? ""; if (!data.startsWith("provider:")) return false; const chatId = ctx.chat?.id; if (!chatId) return true;
  if (data === "provider:close") { clearProviderWizard(chatId); clearIntegrationWizard(chatId); await ctx.answerCallbackQuery({ text: "Closed" }).catch(() => {}); await ctx.deleteMessage().catch(() => {}); return true; }
  if (data === "provider:advanced") { clearProviderWizard(chatId); clearIntegrationWizard(chatId); await ctx.answerCallbackQuery().catch(() => {}); const view = buildAdvancedSettingsView(); await replyWithInlineMenu(ctx, { menuKind: "settings", text: view.text, keyboard: view.keyboard }); return true; }
  await ctx.answerCallbackQuery().catch(() => {});
  if (data === "provider:cancel") { const state = pending.get(chatId); pending.delete(chatId); clearIntegrationWizard(chatId); await renderProvidersMenu(ctx, state?.messageId, "❌ Setup cancelled."); return true; }
  if (data === "provider:add") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; clearIntegrationWizard(chatId); pending.set(chatId, { step: "name", messageId }); await editWizard(ctx, messageId, "➕ Add Custom Provider\n\n1/3 · Provider name\n\nExample: TabiToken"); return true; }
  if (data === "provider:gemini:configure") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; clearIntegrationWizard(chatId); pending.set(chatId, { step: "gemini-chat-key", messageId }); await editWizard(ctx, messageId, `🤖 Configure Gemini\n\nSend your Google AI Studio API key.\n\nModel: ${GEMINI_MODEL}\n🔐 The key is verified before it is stored.`); return true; }
  if (data === "provider:image:menu") { await renderImageAiMenu(ctx); return true; }
  if (data === "provider:image:pollinations:configure") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; pending.set(chatId, { step: "image-pollinations-key", messageId }); await editWizard(ctx, messageId, "🎨 Configure Pollinations\n\nSend your Pollinations API key (pk_ or sk_).\nIt will be verified before storage.\nSupports image generation + editing."); return true; }
  if (data === "provider:image:huggingface:configure") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; pending.set(chatId, { step: "image-huggingface-key", messageId }); await editWizard(ctx, messageId, "🤗 Configure Hugging Face\n\nSend your Hugging Face access token.\nIt will be verified before storage.\nBeta: image generation fallback; editing falls back to another active provider."); return true; }
  if (data === "provider:image:custom:configure") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; pending.set(chatId, { step: "image-custom-base-url", messageId }); await editWizard(ctx, messageId, "🧩 Configure Custom Image AI\n\n1/4 · Base URL\nExample: https://api.example.com/v1"); return true; }
  if (data === "provider:image:pollinations:remove") { await removeImageAiProvider(IMAGE_AI_PROVIDER_IDS.POLLINATIONS_ID); await renderImageAiMenu(ctx, undefined, "🎨 Pollinations disabled."); return true; }
  if (data === "provider:image:huggingface:remove") { await removeImageAiProvider(IMAGE_AI_PROVIDER_IDS.HUGGINGFACE_ID); await renderImageAiMenu(ctx, undefined, "🤗 Hugging Face disabled."); return true; }
  if (data === "provider:image:custom:remove") { await removeImageAiProvider(IMAGE_AI_PROVIDER_IDS.CUSTOM_ID); await renderImageAiMenu(ctx, undefined, "🧩 Custom Image AI disabled."); return true; }
  if (data === "provider:stt:groq:add") { const messageId = callbackMessageId(ctx); if (messageId === null) return true; clearIntegrationWizard(chatId); pending.set(chatId, { step: "groq-stt-key", messageId }); await editWizard(ctx, messageId, "🎤 Configure Groq Voice STT\n\nSend your Groq API key.\n\nThe key is verified against Groq and stored securely on persistent storage. It is never displayed back to Telegram."); return true; }
  if (data === "provider:stt:groq:remove") { const removed = await removeGroqStt(); await renderProvidersMenu(ctx, undefined, removed ? "🎤 Groq Voice STT disabled." : "🎤 Groq Voice STT was not configured."); return true; }
  if (data.startsWith("provider:delete:")) { const id = data.slice("provider:delete:".length); const deleted = await deleteCustomProvider(id); if (deleted) { await restartOpenCodeAfterProviderChange(); await renderProvidersMenu(ctx); } else await ctx.answerCallbackQuery({ text: "Provider not found" }).catch(() => {}); return true; }
  if (data.startsWith("provider:view:")) { const id = data.slice("provider:view:".length); const provider = (await listCustomProviders()).find((item) => item.id === id); if (!provider) { await ctx.answerCallbackQuery({ text: "Provider not found" }).catch(() => {}); return true; } await ctx.api.editMessageText(chatId, callbackMessageId(ctx)!, `🔌 ${provider.name}\n\nBase URL: ${provider.baseURL}\nModels:\n${provider.models.map((m) => `• ${m.name} (${m.id})`).join("\n")}\n\n🔐 API key is stored separately and is never displayed.`, { reply_markup: new InlineKeyboard().text("← Providers", "provider:menu").text("✖ Close", "provider:close") }); return true; }
  if (data === "provider:menu") { await renderProvidersMenu(ctx); return true; }
  return true;
}

export async function handleProviderWizardMessage(ctx: Context): Promise<boolean> { const chatId = ctx.chat?.id; const text = ctx.message?.text?.trim(); const state = chatId ? pending.get(chatId) : undefined; if (!chatId || !text || !state) return false; try {
  if (state.step === "gemini-chat-key") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "🤖 Verifying Gemini API key…\n\n⏳ Checking Gemini model access."); const response = await fetch(`${GEMINI_BASE_URL}/models/${GEMINI_MODEL}`, { headers: { Authorization: `Bearer ${text}` }, signal: AbortSignal.timeout(15_000) }); const detail = await response.text().catch(() => ""); if (!response.ok) throw new Error(`Gemini API key verification failed (HTTP ${response.status})${detail ? `: ${detail.slice(0, 220)}` : "."}`); const payload = JSON.parse(detail) as { name?: string }; if (!payload.name?.endsWith(`/models/${GEMINI_MODEL}`)) throw new Error("Gemini returned an unexpected model verification response."); await saveCustomProvider({ id: GEMINI_PROVIDER_ID, name: "Gemini", baseURL: GEMINI_BASE_URL, apiKey: text, models: [{ id: GEMINI_MODEL, name: "Gemini 3.1 Flash-Lite" }] }); await deleteCustomProvider(LEGACY_GEMINI_IMAGE_PROVIDER_ID); pending.delete(chatId); await restartOpenCodeAfterProviderChange(); await renderProvidersMenu(ctx, state.messageId, `✅ Gemini verified and activated.\n\n🤖 Chat model: ${GEMINI_MODEL}\n💸 Free Tier model`); logger.info(`[Providers] Gemini chat provider verified: ${GEMINI_MODEL}`); return true; }
  if (state.step === "image-pollinations-key") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "🎨 Verifying Pollinations API key…"); await configureBuiltInImageAiProvider(IMAGE_AI_PROVIDER_IDS.POLLINATIONS_ID, text); pending.delete(chatId); await renderImageAiMenu(ctx, state.messageId, "✅ Pollinations API key verified and activated."); return true; }
  if (state.step === "image-huggingface-key") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "🤗 Verifying Hugging Face token…"); await configureBuiltInImageAiProvider(IMAGE_AI_PROVIDER_IDS.HUGGINGFACE_ID, text); pending.delete(chatId); await renderImageAiMenu(ctx, state.messageId, "✅ Hugging Face token verified and activated."); return true; }
  if (state.step === "image-custom-base-url") { const baseURL = text.replace(/\/+$/, ""); try { const parsed = new URL(baseURL); if (parsed.protocol !== "http:" && parsed.protocol !== "https:") throw new Error(); } catch { await editWizard(ctx, state.messageId, "🧩 Configure Custom Image AI\n\n1/4 · Base URL\n\n⚠️ Invalid http(s) URL. Try again."); return true; } state.baseURL = baseURL; state.step = "image-custom-model"; await deleteInput(ctx); await editWizard(ctx, state.messageId, "🧩 Configure Custom Image AI\n\n2/4 · Generation model\n\nExample: flux-1.1-pro"); return true; }
  if (state.step === "image-custom-model") { state.model = text; state.step = "image-custom-edit-model"; await deleteInput(ctx); await editWizard(ctx, state.messageId, "🧩 Configure Custom Image AI\n\n3/4 · Edit model\n\nSend the edit model ID, or type `none` if generation-only."); return true; }
  if (state.step === "image-custom-edit-model") { state.editModel = text.toLowerCase() === "none" ? undefined : text; state.step = "image-custom-key"; await deleteInput(ctx); await editWizard(ctx, state.messageId, "🧩 Configure Custom Image AI\n\n4/4 · API key\n\nSend the key. It will be deleted when Telegram permits it."); return true; }
  if (state.step === "image-custom-key") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "🧩 Verifying Custom Image AI…"); await configureImageAiProvider(IMAGE_AI_PROVIDER_IDS.CUSTOM_ID, text, { baseURL: state.baseURL, model: state.model, editModel: state.editModel }); pending.delete(chatId); await renderImageAiMenu(ctx, state.messageId, "✅ Custom Image AI verified and activated."); return true; }
  if (state.step === "groq-stt-key") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "🎤 Verifying Groq API key…"); await configureGroqStt(text); pending.delete(chatId); await renderProvidersMenu(ctx, state.messageId, "✅ Groq Voice STT verified and activated."); return true; }
  if (state.step === "name") { state.name = text; state.step = "url"; await deleteInput(ctx); await editWizard(ctx, state.messageId, "➕ Add Custom Provider\n\n2/3 · Base URL\n\nExample: https://tabitoken.com/v1"); return true; }
  if (state.step === "url") { const baseURL = text.replace(/\/+$/, ""); let parsed: URL; try { parsed = new URL(baseURL); } catch { await deleteInput(ctx); await editWizard(ctx, state.messageId, "➕ Add Custom Provider\n\n2/3 · Base URL\n\n⚠️ Invalid URL. Try again."); return true; } if (parsed.protocol !== "http:" && parsed.protocol !== "https:") { await deleteInput(ctx); await editWizard(ctx, state.messageId, "➕ Add Custom Provider\n\n⚠️ Only http:// and https:// URLs are supported. Try again."); return true; } state.baseURL = baseURL; state.step = "key"; await deleteInput(ctx); await editWizard(ctx, state.messageId, "➕ Add Custom Provider\n\n3/3 · API key\n\nSend the key as a message. It will be deleted when Telegram permits it."); return true; }
  state.apiKey = text; await deleteInput(ctx); await editWizard(ctx, state.messageId, "🔎 Testing provider and discovering models…"); const models = await discoverModels(state.baseURL!, state.apiKey!); const savedProvider = await saveCustomProvider({ name: state.name!, baseURL: state.baseURL!, apiKey: state.apiKey!, models }); pending.delete(chatId); await restartOpenCodeAfterProviderChange(); await renderProvidersMenu(ctx, state.messageId, `✅ ${savedProvider.name} configured successfully · ${models.length} model${models.length === 1 ? "" : "s"} found`); return true;
 } catch (error) { logger.error("[Providers] Provider wizard failed:", error); const message = error instanceof Error ? error.message : "Unknown error"; await editWizard(ctx, state.messageId, `❌ ${message}\n\nThe key was NOT saved. Send it again to retry, or press Cancel.`).catch(() => {}); return true; } }
