import { describe, expect, it } from "vitest";
import { defined } from "../helpers/defined.js";
import { createMainKeyboard } from "../../src/bot/keyboards/main-reply-keyboard.js";
import { AGENT_MODE_BUTTON_TEXT_PATTERN, isReplyKeyboardButtonText, MODEL_BUTTON_TEXT_PATTERN, QUEUED_PROMPT_BUTTON_TEXT_PATTERN, VARIANT_BUTTON_TEXT_PATTERN } from "../../src/bot/message-patterns.js";
import { formatQueuedPromptButtonLabel } from "../../src/bot/keyboards/queued-prompt-button.js";
function getButtonText(button: string | { text: string }): string { return typeof button === "string" ? button : button.text; }
describe("bot/message-patterns", () => {
  it("matches known model-family labels", () => { expect("🧠 GPT 5.6 Sol").toMatch(MODEL_BUTTON_TEXT_PATTERN); expect("🧠 DeepSeek V4 Flash").toMatch(MODEL_BUTTON_TEXT_PATTERN); });
  it("does not classify arbitrary brain-prefixed prompts as model buttons", () => { expect("🧠 Explain this architecture").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); expect("🧠 Explain this architecture 2026").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); expect("🧠 Big Pickle").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); });
  it("recognises an arbitrary custom model only through the exact current label set", () => { const known = new Set(["🧠 Big Pickle"]); expect(isReplyKeyboardButtonText("🧠 Big Pickle", known)).toBe(true); expect(isReplyKeyboardButtonText("🧠 Explain this architecture 2026", known)).toBe(false); });
  it("matches model button text from main keyboard through the exact label set", () => { const keyboard = createMainKeyboard("build", { providerID: "openrouter", modelID: "openai/gpt-4o" }); const modelButtonText = getButtonText(defined(keyboard.keyboard[2]?.[0])); expect(isReplyKeyboardButtonText(modelButtonText, new Set([modelButtonText]))).toBe(true); });
  it("rejects the old multiline model button format", () => { expect("🧠 cliproxyapi2/gpt-5.3-codex\ncliproxyapi2").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); });
  it("does not treat custom agent labels as model buttons", () => { expect("🤖 Reviewer Agent").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); });
  it("matches current and legacy variant button prefixes", () => { const keyboard = createMainKeyboard("build", { providerID: "openrouter", modelID: "openai/gpt-4o" }); expect("💡 Default").toMatch(VARIANT_BUTTON_TEXT_PATTERN); expect("💭 Default").toMatch(VARIANT_BUTTON_TEXT_PATTERN); expect(getButtonText(defined(keyboard.keyboard[1]?.[1]))).toBe("📦 Compact: OFF"); });
  it("does not match plain prompt text", () => { expect("Create a migration plan").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); expect("Create a migration plan").not.toMatch(AGENT_MODE_BUTTON_TEXT_PATTERN); expect("Create a migration plan").not.toMatch(VARIANT_BUTTON_TEXT_PATTERN); });
  it("matches current and legacy agent button labels with extra descriptors", () => { expect("🤖 Sisyphus (Ultraworker) Agent").toMatch(AGENT_MODE_BUTTON_TEXT_PATTERN); expect("🤖 Sisyphus (Ultraworker) Mode").toMatch(AGENT_MODE_BUTTON_TEXT_PATTERN); expect("🤖 Sisyphus (Ultraworker) Agent").not.toMatch(MODEL_BUTTON_TEXT_PATTERN); });
  it("matches queued prompt button labels", () => { expect(formatQueuedPromptButtonLabel(1, "Fix the bug")).toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect(formatQueuedPromptButtonLabel(12, "Fix the bug")).toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); });
  it("does not treat other button labels or prompts as queued prompts", () => { expect("🧠 openrouter\nopenai/gpt-4o").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect("🛠️ Build Agent").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect("💡 Default").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect("📊 150K / 1.5M (10%)").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect("Create a migration plan").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); expect("❌ do not do that").not.toMatch(QUEUED_PROMPT_BUTTON_TEXT_PATTERN); });
  it("recognises every reply keyboard button label", () => { const keyboard = createMainKeyboard("build", { providerID: "openrouter", modelID: "openai/gpt-4o" }, { tokensUsed: 150000, tokensLimit: 1500000 }); const modelButtonText = getButtonText(defined(keyboard.keyboard[2]?.[0])); expect(isReplyKeyboardButtonText(getButtonText(defined(keyboard.keyboard[0]?.[0])))).toBe(true); expect(isReplyKeyboardButtonText(getButtonText(defined(keyboard.keyboard[0]?.[1])))).toBe(true); expect(isReplyKeyboardButtonText(getButtonText(defined(keyboard.keyboard[1]?.[0])))).toBe(true); expect(isReplyKeyboardButtonText(getButtonText(defined(keyboard.keyboard[1]?.[1])))).toBe(true); expect(isReplyKeyboardButtonText(modelButtonText, new Set([modelButtonText]))).toBe(true); expect(isReplyKeyboardButtonText(formatQueuedPromptButtonLabel(1, "queued"))).toBe(true); expect(isReplyKeyboardButtonText("Create a migration plan")).toBe(false); });
  it("recognises all static main controls", () => { for (const text of ["🕘 History", "💬 New Chat", "⚙️ Settings", "🎨 Image AI", "📦 Compact: ON", "📦 Compact: OFF", "⏸️ Pause", "▶️ Resume", "🛑 Abort"]) expect(isReplyKeyboardButtonText(text), text).toBe(true); });
});
