import { Context, InlineKeyboard } from "grammy";
import { fetchCurrentModel, getModelSelectionLists } from "../../app/services/model-selection-service.js";
import type { FavoriteModel, ModelInfo, ModelSelectionLists, ProviderInfo } from "../../app/types/model.js";
import { config } from "../../config.js";
import { logger } from "../../utils/logger.js";
import { t } from "../../i18n/index.js";
import { replyWithInlineMenu } from "./inline-menu.js";
import { buildModelCenterRoot } from "./model-center-menu.js";

export const MODEL_SEARCH_CALLBACK = "model:search";
export const MODEL_SEARCH_AGAIN_CALLBACK = "model:search:again";
export const MODEL_SEARCH_CANCEL_CALLBACK = "model:search:cancel";
export const MODEL_LIST_CALLBACK_PREFIX = "model:list:";
export const MODEL_ROOT_CALLBACK = "model:root";
export const MODEL_SETTINGS_BACK_CALLBACK = "model:settings_back";
export const MODEL_PROVIDERS_CALLBACK_PREFIX = "model:providers:";
export const MODEL_PROVIDER_CALLBACK_PREFIX = "model:provider:";
export const MODEL_PROVIDER_MODEL_CALLBACK_PREFIX = "model:pick:";

interface ModelsPaginationRange { page: number; totalPages: number; startIndex: number; endIndex: number; }
type ModelListKind = "favorites" | "recent";

export function buildModelListCallback(kind: ModelListKind, index: number): string { return `${MODEL_LIST_CALLBACK_PREFIX}${kind}:${index}`; }
function parseIndex(value: string): number | null { return /^\d+$/.test(value) ? Number.parseInt(value, 10) : null; }
export function parseProvidersPageCallback(data: string): number | null { if (!data.startsWith(MODEL_PROVIDERS_CALLBACK_PREFIX)) return null; return parseIndex(data.slice(MODEL_PROVIDERS_CALLBACK_PREFIX.length)); }
export function parseProviderCallback(data: string): { providerIndex: number; page: number } | null { if (!data.startsWith(MODEL_PROVIDER_CALLBACK_PREFIX)) return null; const parts = data.slice(MODEL_PROVIDER_CALLBACK_PREFIX.length).split(":"); if (parts.length !== 2) return null; const providerIndex = parseIndex(parts[0] ?? ""); const page = parseIndex(parts[1] ?? ""); return providerIndex === null || page === null ? null : { providerIndex, page }; }
export function parseProviderModelCallback(data: string): number | null { if (!data.startsWith(MODEL_PROVIDER_MODEL_CALLBACK_PREFIX)) return null; return parseIndex(data.slice(MODEL_PROVIDER_MODEL_CALLBACK_PREFIX.length)); }
function sameModel(a: ModelInfo | FavoriteModel, b: ModelInfo | FavoriteModel): boolean { return a.providerID === b.providerID && a.modelID === b.modelID; }
function escapeHtml(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function modelLabel(model: FavoriteModel, active: boolean, icon: string): string { return `${active ? "✅" : icon} ${model.modelID}\n${model.providerID}`; }
function buildModelSelectionMenuText(currentModel: ModelInfo | undefined, modelLists: ModelSelectionLists): string { const current = currentModel?.providerID && currentModel.modelID ? ["🟢 <b>Current model</b>", `<code>${escapeHtml(currentModel.modelID)}</code>`, `${escapeHtml(currentModel.providerID)}${currentModel.variant && currentModel.variant !== "default" ? ` · ${escapeHtml(currentModel.variant)}` : ""}`] : ["🟢 <b>Current model</b>", "No model selected"]; const favoriteCount = modelLists.favorites.filter((model) => !currentModel || !sameModel(model, currentModel)).length; const recentCount = modelLists.recent.filter((model) => !currentModel || !sameModel(model, currentModel)).length; return ["🤖 <b>Model Center</b>", "", ...current, "", `⭐ <b>Favorites</b> · ${favoriteCount}`, `🕘 <b>Recent</b> · ${recentCount}`, "", "Choose a model for this chat, or explore the catalog."].join("\n"); }
export async function buildModelSelectionMenu(currentModel?: ModelInfo, modelLists?: ModelSelectionLists): Promise<InlineKeyboard> { const keyboard = new InlineKeyboard(); const lists = modelLists ?? (await getModelSelectionLists()); const active = currentModel?.providerID && currentModel.modelID ? currentModel : undefined; const addButton = (model: FavoriteModel, icon: string, kind: ModelListKind, index: number): void => { if (active && sameModel(model, active)) return; keyboard.text(modelLabel(model, false, icon), buildModelListCallback(kind, index)).row(); }; lists.favorites.forEach((model, index) => addButton(model, "⭐", "favorites", index)); lists.recent.forEach((model, index) => addButton(model, "🕘", "recent", index)); keyboard.text("🔎 Search models", MODEL_SEARCH_CALLBACK).text("🧩 Browse providers", `${MODEL_PROVIDERS_CALLBACK_PREFIX}0`).row(); keyboard.text("← Back", MODEL_SETTINGS_BACK_CALLBACK); if (lists.favorites.length === 0 && lists.recent.length === 0) logger.warn("[ModelHandler] No favorite or recent models found"); return keyboard; }
export async function buildModelRootMenuView(currentModel: ModelInfo | undefined, modelLists: ModelSelectionLists): Promise<{ text: string; keyboard: InlineKeyboard }> { return { text: buildModelSelectionMenuText(currentModel, modelLists), keyboard: await buildModelSelectionMenu(currentModel, modelLists) }; }
function appendPaginationRow(keyboard: InlineKeyboard, page: number, totalPages: number, buildCallback: (page: number) => string): void { if (totalPages <= 1) return; if (page > 0) keyboard.text("‹ Prev", buildCallback(page - 1)); if (page < totalPages - 1) keyboard.text("Next ›", buildCallback(page + 1)); keyboard.row(); }
function appendPageIndicator(text: string, page: number, totalPages: number, indicatorKey: "model.providers.page_indicator" | "model.provider_models.page_indicator"): string { return totalPages <= 1 ? text : `${text}\n\n${t(indicatorKey, { current: String(page + 1), total: String(totalPages) })}`; }
export function buildProvidersMenuView(providers: ProviderInfo[], page: number): { text: string; keyboard: InlineKeyboard; page: number } { const keyboard = new InlineKeyboard(); const { page: normalizedPage, totalPages, startIndex, endIndex } = calculateModelsPaginationRange(providers.length, page, config.bot.modelsListLimit); providers.slice(startIndex, endIndex).forEach((provider, index) => { keyboard.text(`🧩 ${provider.name}\n${provider.modelCount} models`, `${MODEL_PROVIDER_CALLBACK_PREFIX}${startIndex + index}:0`).row(); }); appendPaginationRow(keyboard, normalizedPage, totalPages, (targetPage) => `${MODEL_PROVIDERS_CALLBACK_PREFIX}${targetPage}`); keyboard.text("← Models", MODEL_ROOT_CALLBACK); const baseText = providers.length === 0 ? "🧩 <b>Providers</b>\n\nNo providers are currently available." : "🧩 <b>Providers</b>\n\nChoose a provider to browse its models."; return { text: appendPageIndicator(baseText, normalizedPage, totalPages, "model.providers.page_indicator"), keyboard, page: normalizedPage }; }
export function buildProviderModelsMenuView(provider: ProviderInfo, providerIndex: number, models: FavoriteModel[], page: number, providersPage: number, currentModel?: ModelInfo): { text: string; keyboard: InlineKeyboard; page: number; pageModels: FavoriteModel[] } { const keyboard = new InlineKeyboard(); const { page: normalizedPage, totalPages, startIndex, endIndex } = calculateModelsPaginationRange(models.length, page, config.bot.modelsListLimit); const pageModels = models.slice(startIndex, endIndex); pageModels.forEach((model, index) => { const active = !!currentModel && sameModel(model, currentModel); keyboard.text(modelLabel(model, active, "🤖"), `${MODEL_PROVIDER_MODEL_CALLBACK_PREFIX}${index}`).row(); }); appendPaginationRow(keyboard, normalizedPage, totalPages, (targetPage) => `${MODEL_PROVIDER_CALLBACK_PREFIX}${providerIndex}:${targetPage}`); keyboard.text("← Providers", `${MODEL_PROVIDERS_CALLBACK_PREFIX}${providersPage}`); const baseText = pageModels.length === 0 ? `🧩 <b>${escapeHtml(provider.name)}</b>\n\nNo models are currently available.` : `🧩 <b>${escapeHtml(provider.name)}</b>\n\nChoose a model.`; return { text: appendPageIndicator(baseText, normalizedPage, totalPages, "model.provider_models.page_indicator"), keyboard, page: normalizedPage, pageModels }; }
export function calculateModelsPaginationRange(totalItems: number, page: number, pageSize: number): ModelsPaginationRange { const safePageSize = Math.max(1, pageSize); const totalPages = Math.max(1, Math.ceil(totalItems / safePageSize)); const normalizedPage = Math.min(Math.max(0, page), totalPages - 1); return { page: normalizedPage, totalPages, startIndex: normalizedPage * safePageSize, endIndex: Math.min((normalizedPage + 1) * safePageSize, totalItems) }; }
export async function showModelSelectionMenu(ctx: Context): Promise<void> { try { const view = await buildModelCenterRoot(fetchCurrentModel()); await replyWithInlineMenu(ctx, { menuKind: "model", text: view.text, keyboard: view.keyboard, parseMode: "HTML", metadata: { modelLists: { favorites: [], recent: [] } } }); } catch (err) { logger.error("[ModelHandler] Error showing model menu:", err); await ctx.reply(t("model.menu.error")); } }
