import { Context, InlineKeyboard } from "grammy";
import { fetchCurrentModel, getModelSelectionLists } from "../../app/services/model-selection-service.js";
import type { FavoriteModel, ModelInfo, ModelSelectionLists, ProviderInfo } from "../../app/types/model.js";
import { config } from "../../config.js";
import { logger } from "../../utils/logger.js";
import { t } from "../../i18n/index.js";
import { replyWithInlineMenu } from "./inline-menu.js";

export const MODEL_SEARCH_CALLBACK = "model:search";
export const MODEL_SEARCH_AGAIN_CALLBACK = "model:search:again";
export const MODEL_SEARCH_CANCEL_CALLBACK = "model:search:cancel";
export const MODEL_LIST_CALLBACK_PREFIX = "model:list:";
export const MODEL_ROOT_CALLBACK = "model:root";
export const MODEL_SETTINGS_BACK_CALLBACK = "model:settings_back";
export const MODEL_PROVIDERS_CALLBACK_PREFIX = "model:providers:";
export const MODEL_PROVIDER_CALLBACK_PREFIX = "model:provider:";
export const MODEL_PROVIDER_MODEL_CALLBACK_PREFIX = "model:pick:";
interface ModelsPaginationRange { page: number; totalPages: number; startIndex: number; endIndex: number; }
type ModelListKind = "favorites" | "recent";
export function buildModelListCallback(kind: ModelListKind, index: number): string { return `${MODEL_LIST_CALLBACK_PREFIX}${kind}:${index}`; }
function parseIndex(value: string): number | null { return /^\d+$/.test(value) ? Number.parseInt(value, 10) : null; }
export function parseProvidersPageCallback(data: string): number | null { if (!data.startsWith(MODEL_PROVIDERS_CALLBACK_PREFIX)) return null; return parseIndex(data.slice(MODEL_PROVIDERS_CALLBACK_PREFIX.length)); }
export function parseProviderCallback(data: string): { providerIndex: number; page: number } | null { if (!data.startsWith(MODEL_PROVIDER_CALLBACK_PREFIX)) return null; const parts = data.slice(MODEL_PROVIDER_CALLBACK_PREFIX.length).split(":"); if (parts.length !== 2) return null; const providerIndex = parseIndex(parts[0] ?? ""); const page = parseIndex(parts[1] ?? ""); return providerIndex === null || page === null ? null : { providerIndex, page }; }
export function parseProviderModelCallback(data: string): number | null { if (!data.startsWith(MODEL_PROVIDER_MODEL_CALLBACK_PREFIX)) return null; return parseIndex(data.slice(MODEL_PROVIDER_MODEL_CALLBACK_PREFIX.length)); }
export function calculateModelsPaginationRange(totalItems: number, page: number, pageSize: number): ModelsPaginationRange { const safePageSize = Math.max(1, pageSize); const totalPages = Math.max(1, Math.ceil(totalItems / safePageSize)); const normalizedPage = Math.min(Math.max(0, page), totalPages - 1); return { page: normalizedPage, totalPages, startIndex: normalizedPage * safePageSize, endIndex: Math.min((normalizedPage + 1) * safePageSize, totalItems) }; }
function modelLabel(model: FavoriteModel, active: boolean, icon: string): string { const provider = model.providerID.length > 18 ? `${model.providerID.slice(0, 15)}…` : model.providerID; const name = model.modelID.length > 32 ? `${model.modelID.slice(0, 29)}…` : model.modelID; return `${active ? "✅" : icon} ${name}\n${provider} · verified`; }
function buildModelSelectionMenuText(modelLists: ModelSelectionLists): string { return ["🤖 Model", "", "Choose the model for the current chat.", "", `⭐ Favorites: ${modelLists.favorites.length}`, `🕘 Recent: ${modelLists.recent.length}`].join("\n"); }
export async function buildModelSelectionMenu(currentModel?: ModelInfo, modelLists?: ModelSelectionLists): Promise<InlineKeyboard> { const keyboard = new InlineKeyboard(); const lists = modelLists ?? (await getModelSelectionLists()); const addButton = (model: FavoriteModel, icon: string, kind: ModelListKind, index: number): void => { const active = currentModel?.providerID === model.providerID && currentModel?.modelID === model.modelID; keyboard.text(modelLabel(model, active, icon), buildModelListCallback(kind, index)).row(); }; lists.favorites.forEach((model, index) => addButton(model, "⭐", "favorites", index)); lists.recent.forEach((model, index) => addButton(model, "🕘", "recent", index)); if (lists.favorites.length === 0 && lists.recent.length === 0) logger.warn("[ModelHandler] No favorite or recent models found"); keyboard.text("🔎 Search models", MODEL_SEARCH_CALLBACK).text("🧩 Providers", `${MODEL_PROVIDERS_CALLBACK_PREFIX}0`).row(); keyboard.row().text("← Settings", MODEL_SETTINGS_BACK_CALLBACK); return keyboard; }
export async function buildModelRootMenuView(currentModel: ModelInfo | undefined, modelLists: ModelSelectionLists): Promise<{ text: string; keyboard: InlineKeyboard }> { return { text: buildModelSelectionMenuText(modelLists), keyboard: await buildModelSelectionMenu(currentModel, modelLists) }; }
function appendPaginationRow(keyboard: InlineKeyboard, page: number, totalPages: number, buildCallback: (page: number) => string): void { if (totalPages <= 1) return; if (page > 0) keyboard.text("‹ Prev", buildCallback(page - 1)); if (page < totalPages - 1) keyboard.text("Next ›", buildCallback(page + 1)); keyboard.row(); }
function appendPageIndicator(text: string, page: number, totalPages: number, indicatorKey: "model.providers.page_indicator" | "model.provider_models.page_indicator"): string { return totalPages <= 1 ? text : `${text}\n\n${t(indicatorKey, { current: String(page + 1), total: String(totalPages) })}`; }
export function buildProvidersMenuView(providers: ProviderInfo[], page: number): { text: string; keyboard: InlineKeyboard; page: number } { const keyboard = new InlineKeyboard(); const { page: normalizedPage, totalPages, startIndex, endIndex } = calculateModelsPaginationRange(providers.length, page, config.bot.modelsListLimit); providers.slice(startIndex, endIndex).forEach((provider, index) => keyboard.text(`🧩 ${provider.name}\n${provider.modelCount} models · verified`, `${MODEL_PROVIDER_CALLBACK_PREFIX}${startIndex + index}:0`).row()); appendPaginationRow(keyboard, normalizedPage, totalPages, targetPage => `${MODEL_PROVIDERS_CALLBACK_PREFIX}${targetPage}`); keyboard.text("← Models", MODEL_ROOT_CALLBACK); const baseText = providers.length === 0 ? "🧩 Providers\n\nNo verified providers are currently available." : "🧩 Providers\n\nOnly verified providers and their discovered models are shown."; return { text: appendPageIndicator(baseText, normalizedPage, totalPages, "model.providers.page_indicator"), keyboard, page: normalizedPage }; }
export function buildProviderModelsMenuView(provider: ProviderInfo, providerIndex: number, models: FavoriteModel[], page: number, providersPage: number, currentModel?: ModelInfo): { text: string; keyboard: InlineKeyboard; page: number; pageModels: FavoriteModel[] } { const keyboard = new InlineKeyboard(); const { page: normalizedPage, totalPages, startIndex, endIndex } = calculateModelsPaginationRange(models.length, page, config.bot.modelsListLimit); const pageModels = models.slice(startIndex, endIndex); pageModels.forEach((model, index) => { const active = currentModel?.providerID === model.providerID && currentModel?.modelID === model.modelID; keyboard.text(modelLabel(model, active, "🤖"), `${MODEL_PROVIDER_MODEL_CALLBACK_PREFIX}${index}`).row(); }); appendPaginationRow(keyboard, normalizedPage, totalPages, targetPage => `${MODEL_PROVIDER_CALLBACK_PREFIX}${providerIndex}:${targetPage}`); keyboard.text("← Providers", `${MODEL_PROVIDERS_CALLBACK_PREFIX}${providersPage}`); const baseText = pageModels.length === 0 ? `🧩 ${provider.name}\n\nNo verified models are currently exposed by this provider.` : `🧩 ${provider.name}\n\nSelect a verified model.`; return { text: appendPageIndicator(baseText, normalizedPage, totalPages, "model.provider_models.page_indicator"), keyboard, page: normalizedPage, pageModels }; }
export async function showModelSelectionMenu(ctx: Context): Promise<void> { try { const currentModel = fetchCurrentModel(); const modelLists = await getModelSelectionLists(); const { text, keyboard } = await buildModelRootMenuView(currentModel, modelLists); await replyWithInlineMenu(ctx, { menuKind: "model", text, keyboard, metadata: { modelLists } }); } catch (err) { logger.error("[ModelHandler] Error showing model menu:", err); await ctx.reply(t("model.menu.error")); } }
