import fs from "node:fs/promises";
import path from "node:path";
import { getRuntimePaths } from "../../runtime/paths.js";
import { logger } from "../../utils/logger.js";

export interface CustomProviderModel { id: string; name: string; }
export interface CustomProvider { id: string; name: string; baseURL: string; models: CustomProviderModel[]; createdAt: string; updatedAt: string; }
interface StoredProvider extends CustomProvider { keyFile: string; }
interface StoredSttProvider { provider: "groq"; keyFile: string; model: string; updatedAt: string; }
interface ProviderStoreFile { providers: StoredProvider[]; stt?: StoredSttProvider; }

const STORE_FILENAME = "custom-providers.json";
const PROVIDER_DIR = "providers";
const STT_KEY_FILE = path.join(PROVIDER_DIR, "groq-stt.key");
const GROQ_STT_BASE_URL = "https://api.groq.com/openai/v1";
const GROQ_STT_MODEL = "whisper-large-v3";
const LEGACY_GEMINI_IMAGE_ID = "gemini-image";
const COPILOT_AUTO_PLUGIN = "opencode-github-copilot-auto-model";

function getStorePath(): string { return path.join(getRuntimePaths().appHome, STORE_FILENAME); }
async function readStore(): Promise<ProviderStoreFile> { try { return JSON.parse(await fs.readFile(getStorePath(), "utf8")) as ProviderStoreFile; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { providers: [] }; throw error; } }
async function writeStore(store: ProviderStoreFile): Promise<void> { await fs.mkdir(getRuntimePaths().appHome, { recursive: true }); const temp = `${getStorePath()}.tmp`; await fs.writeFile(temp, JSON.stringify(store, null, 2), { mode: 0o600 }); await fs.rename(temp, getStorePath()); }
function normalizeId(value: string): string { const id = value.trim().toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, ""); if (!id) throw new Error("Provider ID is empty"); return id.slice(0, 48); }
function normalizeBaseURL(value: string): string { const url = new URL(value.trim()); if (url.protocol !== "https:" && url.protocol !== "http:") throw new Error("Base URL must use http:// or https://"); return url.toString().replace(/\/$/, ""); }
function toPublicProvider(provider: StoredProvider): CustomProvider { return { id: provider.id, name: provider.name, baseURL: provider.baseURL, models: provider.models, createdAt: provider.createdAt, updatedAt: provider.updatedAt }; }

export async function listCustomProviders(): Promise<CustomProvider[]> { const store = await readStore(); return store.providers.filter((p) => p.id !== LEGACY_GEMINI_IMAGE_ID).map(toPublicProvider); }
export async function getCustomProvider(id: string): Promise<CustomProvider | undefined> { const store = await readStore(); const provider = store.providers.find((item) => item.id === id); return provider && provider.id !== LEGACY_GEMINI_IMAGE_ID ? toPublicProvider(provider) : undefined; }
export async function getCustomProviderConfig(id: string): Promise<{ apiUrl: string; apiKey: string; models: CustomProviderModel[] } | undefined> { const store = await readStore(); const provider = store.providers.find((item) => item.id === id && item.id !== LEGACY_GEMINI_IMAGE_ID); if (!provider) return undefined; try { const apiKey = (await fs.readFile(path.join(getRuntimePaths().appHome, provider.keyFile), "utf8")).trim(); return apiKey ? { apiUrl: provider.baseURL, apiKey, models: provider.models } : undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
export async function discoverModels(baseURL: string, apiKey: string): Promise<CustomProviderModel[]> { const response = await fetch(`${baseURL.replace(/\/$/, "")}/models`, { headers: { Authorization: `Bearer ${apiKey}` }, signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw new Error(`Model discovery failed: HTTP ${response.status}`); const payload = (await response.json()) as { data?: Array<{ id?: unknown; name?: unknown }> }; const models = (payload.data ?? []).filter((model) => typeof model.id === "string" && model.id.trim()).map((model) => ({ id: model.id as string, name: typeof model.name === "string" && model.name.trim() ? model.name : (model.id as string) })); if (!models.length) throw new Error("Provider returned no models from /models"); return models.slice(0, 100); }
export async function testProvider(baseURL: string, apiKey: string): Promise<void> { await discoverModels(baseURL, apiKey); }

export async function configureGroqStt(apiKey: string): Promise<void> { const key = apiKey.trim(); if (!key) throw new Error("API key is empty"); const response = await fetch(`${GROQ_STT_BASE_URL}/models`, { headers: { Authorization: `Bearer ${key}` }, signal: AbortSignal.timeout(10_000) }); if (!response.ok) { const detail = await response.text().catch(() => ""); throw new Error(`Groq API key verification failed: HTTP ${response.status}${detail ? ` — ${detail.slice(0, 180)}` : ""}`); } const payload = (await response.json()) as { data?: Array<{ id?: unknown }> }; if (!(payload.data ?? []).some((model) => model.id === GROQ_STT_MODEL)) throw new Error(`Groq account does not expose ${GROQ_STT_MODEL}`); const store = await readStore(); const absoluteKeyFile = path.join(getRuntimePaths().appHome, STT_KEY_FILE); await fs.mkdir(path.dirname(absoluteKeyFile), { recursive: true }); await fs.writeFile(absoluteKeyFile, `${key}\n`, { mode: 0o600 }); await writeStore({ ...store, stt: { provider: "groq", keyFile: STT_KEY_FILE, model: GROQ_STT_MODEL, updatedAt: new Date().toISOString() } }); logger.info(`[CustomProvider] Groq STT configured and verified: model=${GROQ_STT_MODEL}`); }
export async function getGroqSttConfig(): Promise<{ apiUrl: string; apiKey: string; model: string } | undefined> { const store = await readStore(); if (!store.stt) return undefined; try { const key = (await fs.readFile(path.join(getRuntimePaths().appHome, store.stt.keyFile), "utf8")).trim(); return key ? { apiUrl: GROQ_STT_BASE_URL, apiKey: key, model: GROQ_STT_MODEL } : undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
export async function isGroqSttConfigured(): Promise<boolean> { return Boolean(await getGroqSttConfig()); }
export async function removeGroqStt(): Promise<boolean> { const store = await readStore(); if (!store.stt) return false; await fs.rm(path.join(getRuntimePaths().appHome, store.stt.keyFile), { force: true }); const next = { ...store }; delete next.stt; await writeStore(next); return true; }

export async function saveCustomProvider(input: { id?: string; name: string; baseURL: string; apiKey: string; models: CustomProviderModel[] }): Promise<CustomProvider> { if (!input.apiKey.trim()) throw new Error("API key is empty"); const id = normalizeId(input.id ?? input.name); const baseURL = normalizeBaseURL(input.baseURL); const now = new Date().toISOString(); const store = await readStore(); const existing = store.providers.find((provider) => provider.id === id); const keyFile = existing?.keyFile ?? path.join(PROVIDER_DIR, `${id}.key`); const absoluteKeyFile = path.join(getRuntimePaths().appHome, keyFile); await fs.mkdir(path.dirname(absoluteKeyFile), { recursive: true }); await fs.writeFile(absoluteKeyFile, `${input.apiKey.trim()}\n`, { mode: 0o600 }); const provider: StoredProvider = { id, name: input.name.trim().slice(0, 80), baseURL, models: input.models.slice(0, 100), keyFile, createdAt: existing?.createdAt ?? now, updatedAt: now }; await writeStore({ ...store, providers: [...store.providers.filter((item) => item.id !== id), provider] }); logger.info(`[CustomProvider] Saved provider ${id} with ${provider.models.length} models`); return toPublicProvider(provider); }
export async function deleteCustomProvider(id: string): Promise<boolean> { const store = await readStore(); const provider = store.providers.find((item) => item.id === id); if (!provider) return false; await fs.rm(path.join(getRuntimePaths().appHome, provider.keyFile), { force: true }); await writeStore({ ...store, providers: store.providers.filter((item) => item.id !== id) }); return true; }
export async function buildOpenCodeCustomConfig(): Promise<string> { const store = await readStore(); const providers: Record<string, unknown> = {}; const appHome = getRuntimePaths().appHome; for (const provider of store.providers.filter((p) => p.id !== LEGACY_GEMINI_IMAGE_ID)) { const keyPath = path.resolve(appHome, provider.keyFile); try { const apiKey = (await fs.readFile(keyPath, "utf8")).trim(); if (!apiKey) { logger.warn(`[CustomProvider] Skipping provider ${provider.id}: key file is empty`); continue; } providers[provider.id] = { npm: "@ai-sdk/openai-compatible", name: provider.name, options: { baseURL: provider.baseURL, apiKey: `{file:${keyPath}}` }, models: Object.fromEntries(provider.models.map((model) => [model.id, { name: model.name }])) }; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") { logger.warn(`[CustomProvider] Skipping provider ${provider.id}: key file missing (${keyPath})`); continue; } throw error; } } return JSON.stringify({ $schema: "https://opencode.ai/config.json", plugin: [COPILOT_AUTO_PLUGIN], provider: providers }, null, 2); }
export async function syncOpenCodeCustomConfig(): Promise<string> { const configDir = path.join(getRuntimePaths().appHome, ".config", "opencode-telegram"); const configPath = path.join(configDir, "custom-providers.json"); await fs.mkdir(configDir, { recursive: true }); await fs.writeFile(configPath, await buildOpenCodeCustomConfig(), { mode: 0o600 }); return configPath; }