import fs from "node:fs/promises";
import path from "node:path";
import { getRuntimePaths } from "../../runtime/paths.js";
import { logger } from "../../utils/logger.js";
import type { ImageAiCapability } from "./image-ai-provider-service.js";

type CostClass = "free" | "free-tier" | "paid" | "unknown";
interface ProviderRecord { id: string; name: string; model: string; editModel?: string; capabilities: ImageAiCapability[]; active: boolean; baseURL: string; keyFile: string; }
interface Store { providers?: ProviderRecord[]; }
export interface FreeImageModel { providerId: string; providerName: string; model: string; editModel?: string; capability: ImageAiCapability; cost: CostClass; reason: string; route?: string; providerModel?: string; }

const STORE = "image-ai-providers.json";
const CACHE_TTL_MS = 15 * 60_000;
let cache: { expiresAt: number; models: FreeImageModel[] } | undefined;
function storePath(): string { return path.join(getRuntimePaths().appHome, STORE); }
async function readStore(): Promise<ProviderRecord[]> { try { const value = JSON.parse(await fs.readFile(storePath(), "utf8")) as Store; return Array.isArray(value.providers) ? value.providers.filter((p) => p?.active && p?.keyFile) : []; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } }
async function readKey(provider: ProviderRecord): Promise<string | undefined> { try { return (await fs.readFile(path.join(getRuntimePaths().appHome, provider.keyFile), "utf8")).trim() || undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
function pricingIsZero(value: unknown): boolean { if (typeof value === "number") return value === 0; if (typeof value === "string") return value.trim() === "0" || value.trim() === "0.0"; if (!value || typeof value !== "object") return false; const obj = value as Record<string, unknown>; const keys = ["input", "output", "prompt", "completion", "image", "images", "input_per_token", "output_per_token"]; const present = keys.filter((key) => key in obj); return present.length > 0 && present.every((key) => pricingIsZero(obj[key])); }
function isExplicitFree(model: Record<string, unknown>): boolean { if (model.is_free === true || model.free === true) return true; if (pricingIsZero(model.pricing)) return true; const id = String(model.id ?? model.name ?? "").toLowerCase(); return /(^|[-/:])free($|[-/:])|:free$/.test(id); }
function isImageModel(model: Record<string, unknown>): boolean { const tags = [model.pipeline_tag, model.task, ...(Array.isArray(model.capabilities) ? model.capabilities : [])].map(String).join(" ").toLowerCase(); const id = String(model.id ?? "").toLowerCase(); return /text-to-image|image-generation|image-edit|images?/.test(tags) || /flux|stable-diffusion|imagen|nano.?banana|image/.test(id); }
async function fetchJson(url: string, key: string): Promise<unknown> { const response = await fetch(url, { headers: { Authorization: `Bearer ${key}`, Accept: "application/json" }, signal: AbortSignal.timeout(15_000) }); const text = await response.text(); let body: unknown = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) throw new Error(`HTTP ${response.status}`); return body; }
async function detectHuggingFace(provider: ProviderRecord, key: string): Promise<FreeImageModel[]> { const body = await fetchJson(`https://router.huggingface.co/v1/models/${encodeURIComponent(provider.model)}`, key) as Record<string, unknown>; const entries = Array.isArray(body?.data) ? body.data : Array.isArray(body?.providers) ? body.providers : []; const result: FreeImageModel[] = []; for (const raw of entries) { if (!raw || typeof raw !== "object") continue; const item = raw as Record<string, unknown>; const providerId = String(item.provider ?? item.provider_id ?? ""); if (!providerId || (item.status && item.status !== "live")) continue; if (item.is_free === true || pricingIsZero(item.pricing)) result.push({ providerId: provider.id, providerName: `${provider.name} / ${providerId}`, model: provider.model, editModel: provider.editModel, capability: "generate", cost: "free", reason: item.is_free === true ? "Hugging Face provider reports is_free=true" : "Hugging Face provider reports zero pricing", route: `https://router.huggingface.co/${providerId}/v1/images/generations`, providerModel: String(item.model ?? item.provider_model ?? provider.model) }); } return result; }
async function detectOpenAiCompatible(provider: ProviderRecord, key: string): Promise<FreeImageModel[]> { const base = provider.baseURL.replace(/\/$/, ""); const body = await fetchJson(`${base}/models`, key) as Record<string, unknown>; const data = Array.isArray(body?.data) ? body.data : Array.isArray(body) ? body : []; const result: FreeImageModel[] = []; for (const raw of data) { if (!raw || typeof raw !== "object") continue; const item = raw as Record<string, unknown>; if (!isImageModel(item) || !isExplicitFree(item)) continue; const id = String(item.id ?? ""); if (!id) continue; const capability: ImageAiCapability = /edit|kontext|inpaint|image-to-image/i.test(id) ? "edit" : "generate"; result.push({ providerId: provider.id, providerName: provider.name, model: id, capability, cost: "free", reason: "Provider /models metadata reports a zero/free price", route: `${base}/images/${capability === "edit" ? "edits" : "generations"}` }); } return result; }
async function detectProvider(provider: ProviderRecord): Promise<FreeImageModel[]> { const key = await readKey(provider); if (!key) return []; if (provider.id === "huggingface") return detectHuggingFace(provider, key); return detectOpenAiCompatible(provider, key); }
export async function detectFreeImageModels(force = false): Promise<FreeImageModel[]> { if (!force && cache && cache.expiresAt > Date.now()) return cache.models; const providers = await readStore(); const results = await Promise.all(providers.map(async (provider) => { try { const found = await detectProvider(provider); logger.info(`[ImageAI] free-model scan provider=${provider.id} found=${found.length}`); return found; } catch (error) { logger.warn(`[ImageAI] free-model scan failed provider=${provider.id}: ${error instanceof Error ? error.message : String(error)}`); return []; } })); const models = results.flat(); cache = { expiresAt: Date.now() + CACHE_TTL_MS, models }; return models; }
export async function getFreeImageModel(capability: ImageAiCapability, force = false): Promise<FreeImageModel | undefined> { const models = await detectFreeImageModels(force); return models.find((model) => model.capability === capability) ?? models.find((model) => model.capability === "generate" && capability === "edit" && model.editModel); }
export function clearFreeImageModelCache(): void { cache = undefined; }
export async function freeImageStatus(): Promise<{ checkedAt: string; models: FreeImageModel[] }> { return { checkedAt: new Date().toISOString(), models: await detectFreeImageModels() }; }
async function imageResponse(response: Response, providerName: string): Promise<{ buffer: Buffer; mimeType: string }> { const text = await response.text(); let body: unknown = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) { const detail = body && typeof body === "object" && "error" in body ? String((body as Record<string, unknown>).error) : `HTTP ${response.status}`; throw new Error(`${providerName}: ${detail}`); } const data = body && typeof body === "object" && Array.isArray((body as Record<string, unknown>).data) ? (body as { data: Array<{ b64_json?: string; url?: string }> }).data[0] : undefined; if (data?.b64_json) return { buffer: Buffer.from(data.b64_json, "base64"), mimeType: "image/png" }; if (data?.url) { const image = await fetch(data.url, { signal: AbortSignal.timeout(120_000) }); if (!image.ok) throw new Error(`${providerName}: image download HTTP ${image.status}`); return { buffer: Buffer.from(await image.arrayBuffer()), mimeType: image.headers.get("content-type") ?? "image/png" }; } throw new Error(`${providerName}: no image data returned`); }
async function executeFreeModel(model: FreeImageModel, prompt: string, image?: Buffer, mimeType?: string): Promise<{ buffer: Buffer; mimeType: string }> { const providers = await readStore(); const provider = providers.find((item) => item.id === model.providerId); if (!provider) throw new Error(`Free image provider ${model.providerId} is no longer configured.`); const key = await readKey(provider); if (!key) throw new Error(`Free image provider ${provider.id} has no API key.`); if (provider.id === "huggingface") { if (image) throw new Error("Hugging Face free image editing is not supported by the verified route."); if (!model.route) throw new Error("Hugging Face free provider route is unavailable."); const response = await fetch(model.route, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: model.providerModel ?? model.model, prompt, n: 1, response_format: "b64_json" }), signal: AbortSignal.timeout(120_000) }); return imageResponse(response, model.providerName); } const base = provider.baseURL.replace(/\/$/, ""); const operation = image ? "edits" : "generations"; const endpoint = `${base}/images/${operation}`; if (image) { const form = new FormData(); form.append("model", model.model); form.append("prompt", prompt); form.append("response_format", "b64_json"); form.append("image", new Blob([new Uint8Array(image)], { type: mimeType ?? "image/png" }), "input.png"); const response = await fetch(endpoint, { method: "POST", headers: { Authorization: `Bearer ${key}` }, body: form, signal: AbortSignal.timeout(120_000) }); return imageResponse(response, model.providerName); } const response = await fetch(endpoint, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: model.model, prompt, n: 1, response_format: "b64_json" }), signal: AbortSignal.timeout(120_000) }); return imageResponse(response, model.providerName); }
export async function generateFreeImage(prompt: string): Promise<{ buffer: Buffer; mimeType: string }> { const errors: string[] = []; const models = (await detectFreeImageModels()).filter((model) => model.capability === "generate"); for (const model of models) { try { logger.info(`[ImageAI] free route provider=${model.providerId} model=${model.model}`); return await executeFreeModel(model, prompt); } catch (error) { const message = error instanceof Error ? error.message : String(error); errors.push(`${model.providerName}: ${message}`); logger.warn(`[ImageAI] free route failed provider=${model.providerId}: ${message}`); clearFreeImageModelCache(); } } throw new Error(errors.length ? `No verified free image model succeeded.\n${errors.join("\n")}` : "No verified free image generation model is currently available."); }
export async function editFreeImage(image: Buffer, mimeType: string, prompt: string): Promise<{ buffer: Buffer; mimeType: string }> { const errors: string[] = []; const models = (await detectFreeImageModels()).filter((model) => model.capability === "edit" || Boolean(model.editModel)); for (const model of models) { try { return await executeFreeModel(model, prompt, image, mimeType); } catch (error) { const message = error instanceof Error ? error.message : String(error); errors.push(`${model.providerName}: ${message}`); logger.warn(`[ImageAI] free edit route failed provider=${model.providerId}: ${message}`); clearFreeImageModelCache(); } } throw new Error(errors.length ? `No verified free image editing model succeeded.\n${errors.join("\n")}` : "No verified free image editing model is currently available."); }
