import { getCurrentModel, setCurrentModel } from "../stores/settings-store.js";
import { config } from "../../config.js";
import { opencodeClient } from "../../opencode/client.js";
import { isServerUnavailableError } from "../../utils/opencode-error.js";
import { logger } from "../../utils/logger.js";
import type { ModelInfo, FavoriteModel, ModelSelectionLists, ProviderInfo } from "../types/model.js";
import path from "node:path";

interface OpenCodeModelState { favorite?: Array<{ providerID?: string; modelID?: string }>; recent?: Array<{ providerID?: string; modelID?: string }>; }
const MODEL_CATALOG_CACHE_TTL_MS = 10 * 60 * 1000;
let cachedValidModelKeys: Set<string> | null = null;
let cachedAllModels: FavoriteModel[] | null = null;
let cachedProviders: ProviderInfo[] | null = null;
let cachedModelsByProvider: Map<string, FavoriteModel[]> | null = null;
let modelCatalogCacheExpiresAt = 0;
let modelCatalogFetchInFlight: Promise<Set<string> | null> | null = null;
const SEARCH_RESULTS_LIMIT = 10;
function getModelKey(providerID: string, modelID: string): string { return `${providerID}/${modelID}`; }
function getEnvDefaultModel(): FavoriteModel | null { const providerID = config.opencode.model.provider; const modelID = config.opencode.model.modelId; return providerID && modelID ? { providerID, modelID } : null; }
function dedupeModels(models: FavoriteModel[]): FavoriteModel[] { const unique = new Map<string, FavoriteModel>(); for (const model of models) { const key = `${model.providerID}/${model.modelID}`; if (!unique.has(key)) unique.set(key, model); } return Array.from(unique.values()); }
function filterModelsByCatalog(models: FavoriteModel[], validModelKeys: Set<string> | null): FavoriteModel[] { return validModelKeys ? models.filter((model) => validModelKeys.has(getModelKey(model.providerID, model.modelID))) : models; }
function logModelCatalogRefreshFailure(error: unknown, type: "error" | "exception"): void { if (isServerUnavailableError(error)) { logger.warn("[ModelManager] OpenCode server is not running; skipping model catalog refresh"); return; } if (type === "error") logger.warn("[ModelManager] Failed to refresh model catalog:", error); else logger.warn("[ModelManager] Error refreshing model catalog:", error); }
async function getValidModelKeys(options?: { force?: boolean | undefined }): Promise<Set<string> | null> {
  if (!options?.force && cachedValidModelKeys && Date.now() < modelCatalogCacheExpiresAt) { logger.debug(`[ModelManager] Model catalog cache hit: models=${cachedValidModelKeys.size}, ttlMs=${modelCatalogCacheExpiresAt - Date.now()}`); return cachedValidModelKeys; }
  if (modelCatalogFetchInFlight) { logger.debug("[ModelManager] Awaiting in-flight model catalog refresh"); return modelCatalogFetchInFlight; }
  modelCatalogFetchInFlight = (async () => {
    try {
      logger.debug("[ModelManager] Refreshing model catalog from OpenCode API");
      const response = await opencodeClient.config.providers();
      if (response.error || !response.data) { logModelCatalogRefreshFailure(response.error, "error"); if (cachedValidModelKeys) { logger.warn("[ModelManager] Using stale model catalog cache after refresh failure"); return cachedValidModelKeys; } return null; }
      const validModelKeys = new Set<string>(); const allModels: FavoriteModel[] = []; const providers: ProviderInfo[] = []; const modelsByProvider = new Map<string, FavoriteModel[]>();
      for (const provider of response.data.providers) { const providerModels: FavoriteModel[] = []; for (const modelID of Object.keys(provider.models)) { validModelKeys.add(getModelKey(provider.id, modelID)); allModels.push({ providerID: provider.id, modelID }); providerModels.push({ providerID: provider.id, modelID }); } providerModels.sort((a,b) => a.modelID.localeCompare(b.modelID)); modelsByProvider.set(provider.id, providerModels); providers.push({ id: provider.id, name: provider.name || provider.id, modelCount: providerModels.length }); }
      providers.sort((a,b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
      cachedValidModelKeys = validModelKeys; cachedAllModels = allModels; cachedProviders = providers; cachedModelsByProvider = modelsByProvider; modelCatalogCacheExpiresAt = Date.now() + MODEL_CATALOG_CACHE_TTL_MS;
      logger.debug(`[ModelManager] Model catalog refreshed: providers=${response.data.providers.length}, models=${validModelKeys.size}`);
      return cachedValidModelKeys;
    } catch (err) { logModelCatalogRefreshFailure(err, "exception"); if (cachedValidModelKeys) { logger.warn("[ModelManager] Using stale model catalog cache after refresh exception"); return cachedValidModelKeys; } return null; }
    finally { modelCatalogFetchInFlight = null; }
  })();
  return modelCatalogFetchInFlight;
}
function normalizeFavoriteModels(state: OpenCodeModelState): FavoriteModel[] { if (!Array.isArray(state.favorite)) return []; return state.favorite.filter((model): model is {providerID:string;modelID:string} => typeof model?.providerID === "string" && model.providerID.length > 0 && typeof model.modelID === "string" && model.modelID.length > 0).map((model) => ({ providerID: model.providerID, modelID: model.modelID })); }
function normalizeRecentModels(state: OpenCodeModelState): FavoriteModel[] { if (!Array.isArray(state.recent)) return []; return state.recent.filter((model): model is {providerID:string;modelID:string} => typeof model?.providerID === "string" && model.providerID.length > 0 && typeof model.modelID === "string" && model.modelID.length > 0).map((model) => ({ providerID: model.providerID, modelID: model.modelID })); }
function getOpenCodeModelStatePath(): string { const xdgStateHome = process.env.XDG_STATE_HOME; if (xdgStateHome && xdgStateHome.trim().length > 0) return path.join(xdgStateHome, "opencode", "model.json"); const homeDir = process.env.HOME || process.env.USERPROFILE || ""; return path.join(homeDir, ".local", "state", "opencode", "model.json"); }
export async function getModelSelectionLists(): Promise<ModelSelectionLists> { const envDefaultModel = getEnvDefaultModel(); try { const fs = await import("fs/promises"); const stateFilePath = getOpenCodeModelStatePath(); const content = await fs.readFile(stateFilePath, "utf-8"); const state = JSON.parse(content) as OpenCodeModelState; const rawFavorites = normalizeFavoriteModels(state); const rawRecent = normalizeRecentModels(state); const validModelKeys = rawFavorites.length > 0 || rawRecent.length > 0 ? await getValidModelKeys() : null; const validatedFavorites = filterModelsByCatalog(rawFavorites, validModelKeys); const validatedRecent = filterModelsByCatalog(rawRecent, validModelKeys); const favorites = envDefaultModel ? dedupeModels([...validatedFavorites, envDefaultModel]) : validatedFavorites; if (rawFavorites.length === 0 && envDefaultModel) logger.info(`[ModelManager] No favorites in ${stateFilePath}, using config model as favorite`); if (favorites.length === 0) logger.warn(`[ModelManager] No favorites in ${stateFilePath}`); const filteredOutFavorites = rawFavorites.length - validatedFavorites.length; const filteredOutRecent = rawRecent.length - validatedRecent.length; if (filteredOutFavorites > 0 || filteredOutRecent > 0) logger.info(`[ModelManager] Filtered unavailable models from OpenCode state: favoritesRemoved=${filteredOutFavorites}, recentRemoved=${filteredOutRecent}`); const favoriteKeys = new Set(favorites.map((model) => getModelKey(model.providerID, model.modelID))); const recent = dedupeModels(validatedRecent).filter((model) => !favoriteKeys.has(getModelKey(model.providerID, model.modelID))); logger.debug(`[ModelManager] Loaded model selection lists from ${stateFilePath}: favorites=${favorites.length}, recent=${recent.length}`); return { favorites, recent }; } catch (err) { if (envDefaultModel) { logger.warn("[ModelManager] Failed to load OpenCode model state, using config model as favorite:", err); return { favorites: [envDefaultModel], recent: [] }; } logger.error("[ModelManager] Failed to load OpenCode model state:", err); return { favorites: [], recent: [] }; } }
export async function reconcileStoredModelSelection(options?: { forceCatalogRefresh?: boolean }): Promise<void> { const currentModel = getCurrentModel(); if (!currentModel?.providerID || !currentModel.modelID) return; const validModelKeys = await getValidModelKeys({ force: options?.forceCatalogRefresh }); if (!validModelKeys) { logger.warn("[ModelManager] Skipping stored model validation: model catalog unavailable"); return; } const currentModelKey = getModelKey(currentModel.providerID, currentModel.modelID); if (validModelKeys.has(currentModelKey)) return; const envDefaultModel = getEnvDefaultModel(); if (!envDefaultModel) { logger.warn(`[ModelManager] Stored model ${currentModelKey} is unavailable and env default model is missing`); return; } const fallbackKey = getModelKey(envDefaultModel.providerID, envDefaultModel.modelID); logger.warn(`[ModelManager] Stored model ${currentModelKey} is unavailable, falling back to ${fallbackKey}`); setCurrentModel({ providerID: envDefaultModel.providerID, modelID: envDefaultModel.modelID, variant: "default" }); }
export function __resetModelCatalogCacheForTests(): void { cachedValidModelKeys = null; cachedAllModels = null; cachedProviders = null; cachedModelsByProvider = null; modelCatalogCacheExpiresAt = 0; modelCatalogFetchInFlight = null; }
export async function getFavoriteModels(): Promise<FavoriteModel[]> { const { favorites } = await getModelSelectionLists(); return favorites; }
export async function getProviders(): Promise<ProviderInfo[]> { await getValidModelKeys({ force: true }); if (!cachedProviders) { logger.warn("[ModelManager] Model catalog unavailable, no providers to show"); return []; } return cachedProviders; }
export async function getProviderModels(providerID: string): Promise<FavoriteModel[]> { await getValidModelKeys({ force: true }); if (!cachedModelsByProvider) { logger.warn("[ModelManager] Model catalog unavailable, no provider models to show"); return []; } return cachedModelsByProvider.get(providerID) ?? []; }
export async function searchModels(query: string): Promise<FavoriteModel[]> { const normalizedQuery = query.trim().toLowerCase(); if (!normalizedQuery) return []; const validKeys = await getValidModelKeys({ force: true }); if (!validKeys || !cachedAllModels) { logger.warn("[ModelManager] Model catalog unavailable, skipping search"); return []; } return cachedAllModels.filter((model) => getModelKey(model.providerID, model.modelID).toLowerCase().includes(normalizedQuery)).sort((a,b) => getModelKey(a.providerID,a.modelID).localeCompare(getModelKey(b.providerID,b.modelID))).slice(0, SEARCH_RESULTS_LIMIT); }
export function fetchCurrentModel(): ModelInfo { return getStoredModel(); }
export function selectModel(modelInfo: ModelInfo): void { logger.info(`[ModelManager] Selected model: ${modelInfo.providerID}/${modelInfo.modelID}`); setCurrentModel(modelInfo); }
export function getStoredModel(): ModelInfo { const storedModel = getCurrentModel(); if (storedModel) { if (!storedModel.variant) storedModel.variant = "default"; return storedModel; } if (config.opencode.model.provider && config.opencode.model.modelId) return { providerID: config.opencode.model.provider, modelID: config.opencode.model.modelId, variant: "default" }; logger.warn("[ModelManager] No model found in settings or config, returning empty model"); return { providerID: "", modelID: "", variant: "default" }; }
